### ISSUE TITLE
cannot import name 'build_samplers_dict' from 'scripts.xy_grid'

### ISSUE THREAD

**Issue by Harvester62** [stysmmaker/stable-diffusion-webui-randomize#10]
After the today's SD Web UI update (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/6074175faa751dde933aa8e15cd687ca4e4b4a23) I get this error in the console:

Error loading script: randomize.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-randomize\scripts\randomize.py", line 10, in <module>
    from scripts.xy_grid import build_samplers_dict
ImportError: cannot import name 'build_samplers_dict' from 'scripts.xy_grid' (C:\stable-diffusion-webui\scripts\xy_grid.py)

**Comment by csmit195** [comment]
Same +1

**Comment by derspanier1** [comment]
same + 1

**Comment by stysmmaker** [comment]
This should be resolved by 17c4ad3d156b439ae49f2d66cf1f63422aec37df now
